module test and updates

diff --git a/4-general/13-vwan-er-hairpin/output/probe-cloud-config.yml b/4-general/13-vwan-er-hairpin/output/probe-cloud-config.yml
--- a/4-general/13-vwan-er-hairpin/output/probe-cloud-config.yml
+++ b/4-general/13-vwan-er-hairpin/output/probe-cloud-config.yml
@@ -171,7 +171,6 @@ write_files:
       apt install -y python3-pip python3-dev python3-venv unzip jq tcpdump dnsutils net-tools nmap apache2-utils iperf3
       
       curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
-      az login --identity || true
       
       ########################################################
       # test scripts (ipv4)
@@ -182,6 +181,7 @@ write_files:
       cat <<'EOF' > /usr/local/bin/ping-ipv4
       echo -e "\n ping ipv4 ...\n"
       echo "branch1 - 10.10.0.5 -$(timeout 3 ping -4 -qc2 -W1 10.10.0.5 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
+      echo "branch2 - 10.20.0.5 -$(timeout 3 ping -4 -qc2 -W1 10.20.0.5 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
       echo "hub1    - 10.11.0.5 -$(timeout 3 ping -4 -qc2 -W1 10.11.0.5 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
       echo "spoke1  - 10.1.0.5 -$(timeout 3 ping -4 -qc2 -W1 10.1.0.5 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
       echo "spoke2  - 10.2.0.5 -$(timeout 3 ping -4 -qc2 -W1 10.2.0.5 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
@@ -194,6 +194,7 @@ write_files:
       cat <<'EOF' > /usr/local/bin/ping-dns4
       echo -e "\n ping dns ipv4 ...\n"
       echo "branch1vm.corp - $(timeout 3 dig +short branch1vm.corp | tail -n1) -$(timeout 3 ping -4 -qc2 -W1 branch1vm.corp 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
+      echo "branch2vm.corp - $(timeout 3 dig +short branch2vm.corp | tail -n1) -$(timeout 3 ping -4 -qc2 -W1 branch2vm.corp 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
       echo "hub1vm.eu.az.corp - $(timeout 3 dig +short hub1vm.eu.az.corp | tail -n1) -$(timeout 3 ping -4 -qc2 -W1 hub1vm.eu.az.corp 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
       echo "spoke1vm.eu.az.corp - $(timeout 3 dig +short spoke1vm.eu.az.corp | tail -n1) -$(timeout 3 ping -4 -qc2 -W1 spoke1vm.eu.az.corp 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
       echo "spoke2vm.eu.az.corp - $(timeout 3 dig +short spoke2vm.eu.az.corp | tail -n1) -$(timeout 3 ping -4 -qc2 -W1 spoke2vm.eu.az.corp 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
@@ -206,6 +207,7 @@ write_files:
       cat <<'EOF' > /usr/local/bin/curl-ipv4
       echo -e "\n curl ipv4 ...\n"
       echo  "$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null 10.10.0.5) - branch1 [10.10.0.5]"
+      echo  "$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null 10.20.0.5) - branch2 [10.20.0.5]"
       echo  "$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null 10.11.0.5) - hub1    [10.11.0.5]"
       echo  "$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null 10.1.0.5) - spoke1  [10.1.0.5]"
       echo  "$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null 10.2.0.5) - spoke2  [10.2.0.5]"
@@ -218,6 +220,7 @@ write_files:
       cat <<'EOF' > /usr/local/bin/curl-dns4
       echo -e "\n curl dns ipv4 ...\n"
       echo  "$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null branch1vm.corp) - branch1vm.corp"
+      echo  "$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null branch2vm.corp) - branch2vm.corp"
       echo  "$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null hub1vm.eu.az.corp) - hub1vm.eu.az.corp"
       echo  "$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null spoke3pls.eu.az.corp) - spoke3pls.eu.az.corp"
       echo  "$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null spoke1vm.eu.az.corp) - spoke1vm.eu.az.corp"
@@ -234,6 +237,9 @@ write_files:
       echo -e "\nbranch1"
       echo -e "-------------------------------------"
       timeout 9 tracepath -4 10.10.0.5
+      echo -e "\nbranch2"
+      echo -e "-------------------------------------"
+      timeout 9 tracepath -4 10.20.0.5
       echo -e "\nhub1   "
       echo -e "-------------------------------------"
       timeout 9 tracepath -4 10.11.0.5
@@ -258,6 +264,7 @@ write_files:
       cat <<'EOF' > /usr/local/bin/ping-ipv6
       echo -e "\n ping ipv6 ...\n"
       echo "branch1 - fd00:db8:10::5 -$(timeout 3 ping -6 -qc2 -W1 fd00:db8:10::5 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
+      echo "branch2 - fd00:db8:20::5 -$(timeout 3 ping -6 -qc2 -W1 fd00:db8:20::5 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
       echo "hub1    - fd00:db8:11::5 -$(timeout 3 ping -6 -qc2 -W1 fd00:db8:11::5 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
       echo "spoke1  - fd00:db8:1::5 -$(timeout 3 ping -6 -qc2 -W1 fd00:db8:1::5 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
       echo "spoke2  - fd00:db8:2::5 -$(timeout 3 ping -6 -qc2 -W1 fd00:db8:2::5 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
@@ -270,6 +277,7 @@ write_files:
       cat <<'EOF' > /usr/local/bin/ping-dns6
       echo -e "\n ping dns ipv6 ...\n"
       echo "branch1vm.corp - $(timeout 3 dig AAAA +short branch1vm.corp | tail -n1) -$(timeout 3 ping -6 -qc2 -W1 branch1vm.corp 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
+      echo "branch2vm.corp - $(timeout 3 dig AAAA +short branch2vm.corp | tail -n1) -$(timeout 3 ping -6 -qc2 -W1 branch2vm.corp 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
       echo "hub1vm.eu.az.corp - $(timeout 3 dig AAAA +short hub1vm.eu.az.corp | tail -n1) -$(timeout 3 ping -6 -qc2 -W1 hub1vm.eu.az.corp 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
       echo "spoke1vm.eu.az.corp - $(timeout 3 dig AAAA +short spoke1vm.eu.az.corp | tail -n1) -$(timeout 3 ping -6 -qc2 -W1 spoke1vm.eu.az.corp 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
       echo "spoke2vm.eu.az.corp - $(timeout 3 dig AAAA +short spoke2vm.eu.az.corp | tail -n1) -$(timeout 3 ping -6 -qc2 -W1 spoke2vm.eu.az.corp 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
@@ -282,6 +290,7 @@ write_files:
       cat <<'EOF' > /usr/local/bin/curl-ipv6
       echo -e "\n curl ipv6 ...\n"
       echo  "$(timeout 3 curl -6 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null [fd00:db8:10::5]) - branch1 [fd00:db8:10::5]"
+      echo  "$(timeout 3 curl -6 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null [fd00:db8:20::5]) - branch2 [fd00:db8:20::5]"
       echo  "$(timeout 3 curl -6 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null [fd00:db8:11::5]) - hub1    [fd00:db8:11::5]"
       echo  "$(timeout 3 curl -6 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null [fd00:db8:1::5]) - spoke1  [fd00:db8:1::5]"
       echo  "$(timeout 3 curl -6 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null [fd00:db8:2::5]) - spoke2  [fd00:db8:2::5]"
@@ -294,6 +303,7 @@ write_files:
       cat <<'EOF' > /usr/local/bin/curl-dns6
       echo -e "\n curl dns ipv6 ...\n"
       echo  "$(timeout 3 curl -6 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null branch1vm.corp) - branch1vm.corp"
+      echo  "$(timeout 3 curl -6 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null branch2vm.corp) - branch2vm.corp"
       echo  "$(timeout 3 curl -6 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null hub1vm.eu.az.corp) - hub1vm.eu.az.corp"
       echo  "$(timeout 3 curl -6 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null spoke3pls.eu.az.corp) - spoke3pls.eu.az.corp"
       echo  "$(timeout 3 curl -6 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null spoke1vm.eu.az.corp) - spoke1vm.eu.az.corp"
@@ -310,6 +320,9 @@ write_files:
       echo -e "\nbranch1"
       echo -e "-------------------------------------"
       timeout 9 tracepath -6 fd00:db8:10::5
+      echo -e "\nbranch2"
+      echo -e "-------------------------------------"
+      timeout 9 tracepath -6 fd00:db8:20::5
       echo -e "\nhub1   "
       echo -e "-------------------------------------"
       timeout 9 tracepath -6 fd00:db8:11::5
@@ -325,9 +338,9 @@ write_files:
       EOF
       chmod a+x /usr/local/bin/trace-ipv6
       
-      ########################################################
+      #########################################################
       # other scripts
-      ########################################################
+      #########################################################
       
       # dns-info
       
@@ -339,7 +352,7 @@ write_files:
       
       # azure service tester
       
-      tee /usr/local/bin/crawlz <<'EOF'
+      cat <<'EOF' > /usr/local/bin/crawlz
       sudo bash -c "cd /var/lib/azure/crawler/app && ./crawler.sh"
       EOF
       chmod a+x /usr/local/bin/crawlz
@@ -352,6 +365,7 @@ write_files:
       
       cat <<'EOF' > /usr/local/bin/light-traffic
       nping -c 5 --tcp-connect -p 80,8080 branch1vm.corp > /dev/null 2>&1
+      nping -c 5 --tcp-connect -p 80,8080 branch2vm.corp > /dev/null 2>&1
       nping -c 5 --tcp-connect -p 80,8080 spoke3pls.eu.az.corp > /dev/null 2>&1
       nping -c 5 --tcp-connect -p 80,8080 spoke1vm.eu.az.corp > /dev/null 2>&1
       nping -c 5 --tcp-connect -p 80,8080 spoke2vm.eu.az.corp > /dev/null 2>&1
@@ -366,6 +380,7 @@ write_files:
       i=0
       while [ $i -lt 5 ]; do
           ab -n $1 -c $2 branch1vm.corp > /dev/null 2>&1
+          ab -n $1 -c $2 branch2vm.corp > /dev/null 2>&1
           ab -n $1 -c $2 spoke3pls.eu.az.corp > /dev/null 2>&1
           ab -n $1 -c $2 spoke1vm.eu.az.corp > /dev/null 2>&1
           ab -n $1 -c $2 spoke2vm.eu.az.corp > /dev/null 2>&1
@@ -384,6 +399,7 @@ write_files:
       
       cat <<'EOF' > /usr/local/bin/light-traffic-ipv6
       nping -c 5 -6 --tcp-connect -p 80,8080 branch1vm.corp > /dev/null 2>&1
+      nping -c 5 -6 --tcp-connect -p 80,8080 branch2vm.corp > /dev/null 2>&1
       nping -c 5 -6 --tcp-connect -p 80,8080 spoke3pls.eu.az.corp > /dev/null 2>&1
       nping -c 5 -6 --tcp-connect -p 80,8080 spoke1vm.eu.az.corp > /dev/null 2>&1
       nping -c 5 -6 --tcp-connect -p 80,8080 spoke2vm.eu.az.corp > /dev/null 2>&1
@@ -414,6 +430,14 @@ write_files:
           exit 1
         else
           echo "target: branch1vm.corp passed"
+        fi
+          ab -s 3 -n $1 -c $2 [$(get_ipv6 branch2vm.corp)]/ > /dev/null 2>&1
+        # check if ab command was successful
+        if [ $? -ne 0 ]; then
+          echo "target: branch2vm.corp failed"
+          exit 1
+        else
+          echo "target: branch2vm.corp passed"
         fi
           ab -s 3 -n $1 -c $2 [$(get_ipv6 spoke3pls.eu.az.corp)]/ > /dev/null 2>&1
         # check if ab command was successful
@@ -469,8 +493,6 @@ write_files:
       
 
 runcmd:
-  - systemctl enable docker
-  - systemctl start docker
   - bash /var/lib/azure/init/startup.sh
   - docker-compose -f /var/lib/azure/fastapi/docker-compose-app1-80.yml up -d
   - docker-compose -f /var/lib/azure/fastapi/docker-compose-app2-8080.yml up -d
