renamed er lab

diff --git a/4-general/08-network-paths-er-vpn/output/probe-cloud-config.yml b/4-general/08-network-paths-er-vpn/output/probe-cloud-config.yml
--- a/4-general/08-network-paths-er-vpn/output/probe-cloud-config.yml
+++ b/4-general/08-network-paths-er-vpn/output/probe-cloud-config.yml
@@ -177,51 +177,51 @@ write_files:
       
       # ping-ipv4
       
-      cat <<EOF > /usr/local/bin/ping-ipv4
+      cat <<'EOF' > /usr/local/bin/ping-ipv4
       echo -e "\n ping ipv4 ...\n"
-      echo "branch2 - 10.20.0.5 -\$(timeout 3 ping -4 -qc2 -W1 10.20.0.5 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "\$5" ms":"NA") }')"
-      echo "hub1    - 10.11.0.5 -\$(timeout 3 ping -4 -qc2 -W1 10.11.0.5 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "\$5" ms":"NA") }')"
-      echo "spoke1  - 10.1.0.5 -\$(timeout 3 ping -4 -qc2 -W1 10.1.0.5 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "\$5" ms":"NA") }')"
-      echo "internet - icanhazip.com -\$(timeout 3 ping -4 -qc2 -W1 icanhazip.com 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "\$5" ms":"NA") }')"
+      echo "branch2 - 10.20.0.5 -$(timeout 3 ping -4 -qc2 -W1 10.20.0.5 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
+      echo "hub1    - 10.11.0.5 -$(timeout 3 ping -4 -qc2 -W1 10.11.0.5 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
+      echo "spoke1  - 10.1.0.5 -$(timeout 3 ping -4 -qc2 -W1 10.1.0.5 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
+      echo "internet - icanhazip.com -$(timeout 3 ping -4 -qc2 -W1 icanhazip.com 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
       EOF
       chmod a+x /usr/local/bin/ping-ipv4
       
       # ping-dns4
       
-      cat <<EOF > /usr/local/bin/ping-dns4
+      cat <<'EOF' > /usr/local/bin/ping-dns4
       echo -e "\n ping dns ipv4 ...\n"
-      echo "branch2vm.corp - \$(timeout 3 dig +short branch2vm.corp | tail -n1) -\$(timeout 3 ping -4 -qc2 -W1 branch2vm.corp 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "\$5" ms":"NA") }')"
-      echo "hub1vm.eu.az.corp - \$(timeout 3 dig +short hub1vm.eu.az.corp | tail -n1) -\$(timeout 3 ping -4 -qc2 -W1 hub1vm.eu.az.corp 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "\$5" ms":"NA") }')"
-      echo "spoke1vm.eu.az.corp - \$(timeout 3 dig +short spoke1vm.eu.az.corp | tail -n1) -\$(timeout 3 ping -4 -qc2 -W1 spoke1vm.eu.az.corp 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "\$5" ms":"NA") }')"
-      echo "icanhazip.com - \$(timeout 3 dig +short icanhazip.com | tail -n1) -\$(timeout 3 ping -4 -qc2 -W1 icanhazip.com 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "\$5" ms":"NA") }')"
+      echo "branch2vm.corp - $(timeout 3 dig +short branch2vm.corp | tail -n1) -$(timeout 3 ping -4 -qc2 -W1 branch2vm.corp 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
+      echo "hub1vm.eu.az.corp - $(timeout 3 dig +short hub1vm.eu.az.corp | tail -n1) -$(timeout 3 ping -4 -qc2 -W1 hub1vm.eu.az.corp 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
+      echo "spoke1vm.eu.az.corp - $(timeout 3 dig +short spoke1vm.eu.az.corp | tail -n1) -$(timeout 3 ping -4 -qc2 -W1 spoke1vm.eu.az.corp 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
+      echo "icanhazip.com - $(timeout 3 dig +short icanhazip.com | tail -n1) -$(timeout 3 ping -4 -qc2 -W1 icanhazip.com 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"NA") }')"
       EOF
       chmod a+x /usr/local/bin/ping-dns4
       
       # curl-ipv4
       
-      cat <<EOF > /usr/local/bin/curl-ipv4
+      cat <<'EOF' > /usr/local/bin/curl-ipv4
       echo -e "\n curl ipv4 ...\n"
-      echo  "\$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null [10.20.0.5]) - branch2 [10.20.0.5]"
-      echo  "\$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null [10.11.0.5]) - hub1    [10.11.0.5]"
-      echo  "\$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null [10.1.0.5]) - spoke1  [10.1.0.5]"
-      echo  "\$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null [icanhazip.com]) - internet [icanhazip.com]"
+      echo  "$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null [10.20.0.5]) - branch2 [10.20.0.5]"
+      echo  "$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null [10.11.0.5]) - hub1    [10.11.0.5]"
+      echo  "$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null [10.1.0.5]) - spoke1  [10.1.0.5]"
+      echo  "$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null [icanhazip.com]) - internet [icanhazip.com]"
       EOF
       chmod a+x /usr/local/bin/curl-ipv4
       
       # curl-dns4
       
-      cat <<EOF > /usr/local/bin/curl-dns4
+      cat <<'EOF' > /usr/local/bin/curl-dns4
       echo -e "\n curl dns ipv4 ...\n"
-      echo  "\$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null branch2vm.corp) - branch2vm.corp"
-      echo  "\$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null hub1vm.eu.az.corp) - hub1vm.eu.az.corp"
-      echo  "\$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null spoke1vm.eu.az.corp) - spoke1vm.eu.az.corp"
-      echo  "\$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null icanhazip.com) - icanhazip.com"
+      echo  "$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null branch2vm.corp) - branch2vm.corp"
+      echo  "$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null hub1vm.eu.az.corp) - hub1vm.eu.az.corp"
+      echo  "$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null spoke1vm.eu.az.corp) - spoke1vm.eu.az.corp"
+      echo  "$(timeout 3 curl -4 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null icanhazip.com) - icanhazip.com"
       EOF
       chmod a+x /usr/local/bin/curl-dns4
       
       # trace-ipv4
       
-      cat <<EOF > /usr/local/bin/trace-ipv4
+      cat <<'EOF' > /usr/local/bin/trace-ipv4
       echo -e "\n trace ipv4 ...\n"
       echo -e "\nbranch2"
       echo -e "-------------------------------------"
@@ -244,39 +244,39 @@ write_files:
       
       # ping-ipv6
       
-      cat <<EOF > /usr/local/bin/ping-ipv6
+      cat <<'EOF' > /usr/local/bin/ping-ipv6
       echo -e "\n ping ipv6 ...\n"
       EOF
       chmod a+x /usr/local/bin/ping-ipv6
       
       # ping-dns6
       
-      cat <<EOF > /usr/local/bin/ping-dns6
+      cat <<'EOF' > /usr/local/bin/ping-dns6
       echo -e "\n ping dns ipv6 ...\n"
       EOF
       chmod a+x /usr/local/bin/ping-dns6
       
       # curl-ipv6
       
-      cat <<EOF > /usr/local/bin/curl-ipv6
+      cat <<'EOF' > /usr/local/bin/curl-ipv6
       echo -e "\n curl ipv6 ...\n"
       EOF
       chmod a+x /usr/local/bin/curl-ipv6
       
       # curl-dns6
       
-      cat <<EOF > /usr/local/bin/curl-dns6
+      cat <<'EOF' > /usr/local/bin/curl-dns6
       echo -e "\n curl dns ipv6 ...\n"
-      echo  "\$(timeout 3 curl -6 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null branch2vm.corp) - branch2vm.corp"
-      echo  "\$(timeout 3 curl -6 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null hub1vm.eu.az.corp) - hub1vm.eu.az.corp"
-      echo  "\$(timeout 3 curl -6 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null spoke1vm.eu.az.corp) - spoke1vm.eu.az.corp"
-      echo  "\$(timeout 3 curl -6 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null icanhazip.com) - icanhazip.com"
+      echo  "$(timeout 3 curl -6 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null branch2vm.corp) - branch2vm.corp"
+      echo  "$(timeout 3 curl -6 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null hub1vm.eu.az.corp) - hub1vm.eu.az.corp"
+      echo  "$(timeout 3 curl -6 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null spoke1vm.eu.az.corp) - spoke1vm.eu.az.corp"
+      echo  "$(timeout 3 curl -6 -kL --max-time 3.0 -H 'Cache-Control: no-cache' -w "%{http_code} (%{time_total}s) - %{remote_ip}" -s -o /dev/null icanhazip.com) - icanhazip.com"
       EOF
       chmod a+x /usr/local/bin/curl-dns6
       
       # trace-ipv6
       
-      cat <<EOF > /usr/local/bin/trace-ipv6
+      cat <<'EOF' > /usr/local/bin/trace-ipv6
       echo -e "\n trace ipv6 ...\n"
       EOF
       chmod a+x /usr/local/bin/trace-ipv6
@@ -287,7 +287,7 @@ write_files:
       
       # dns-info
       
-      cat <<EOF > /usr/local/bin/dns-info
+      cat <<'EOF' > /usr/local/bin/dns-info
       echo -e "\n resolvectl ...\n"
       resolvectl status
       EOF
@@ -306,20 +306,20 @@ write_files:
       
       # light-traffic generator
       
-      cat <<EOF > /usr/local/bin/light-traffic
-      nping -c 10 --tcp -p 80 branch2vm.corp > /dev/null 2>&1
-      nping -c 10 --tcp -p 80 spoke1vm.eu.az.corp > /dev/null 2>&1
+      cat <<'EOF' > /usr/local/bin/light-traffic
+      nping -c 5 --tcp-connect -p 80,8080 branch2vm.corp > /dev/null 2>&1
+      nping -c 5 --tcp-connect -p 80,8080 spoke1vm.eu.az.corp > /dev/null 2>&1
       EOF
       chmod a+x /usr/local/bin/light-traffic
       
       # heavy-traffic generator
       
-      cat <<EOF > /usr/local/bin/heavy-traffic
+      cat <<'EOF' > /usr/local/bin/heavy-traffic
       #! /bin/bash
       i=0
-      while [ \$i -lt 8 ]; do
-          ab -n \$1 -c \$2 branch2vm.corp > /dev/null 2>&1
-          ab -n \$1 -c \$2 spoke1vm.eu.az.corp > /dev/null 2>&1
+      while [ $i -lt 5 ]; do
+          ab -n $1 -c $2 branch2vm.corp > /dev/null 2>&1
+          ab -n $1 -c $2 spoke1vm.eu.az.corp > /dev/null 2>&1
           let i=i+1
         sleep 5
       done
@@ -327,15 +327,65 @@ write_files:
       chmod a+x /usr/local/bin/heavy-traffic
       
       ########################################################
+      # traffic generators (ipv6)
+      ########################################################
+      
+      # light-traffic generator
+      
+      cat <<'EOF' > /usr/local/bin/light-traffic-ipv6
+      nping -c 5 -6 --tcp-connect -p 80,8080 branch2vm.corp > /dev/null 2>&1
+      nping -c 5 -6 --tcp-connect -p 80,8080 spoke1vm.eu.az.corp > /dev/null 2>&1
+      EOF
+      chmod a+x /usr/local/bin/light-traffic-ipv6
+      
+      # heavy-traffic generator
+      
+      cat <<'EOF' > /usr/local/bin/heavy-traffic-ipv6
+      #! /bin/bash
+      
+      get_ipv6() {
+        ipv6=$(host -t AAAA $1 | awk '/has IPv6 address/ {print $5}')
+        if [ -z "$ipv6" ]; then
+          echo $1
+        else
+          echo $ipv6
+        fi
+      }
+      
+      i=0
+      while [ $i -lt 8 ]; do
+          ab -s 3 -n $1 -c $2 [$(get_ipv6 branch2vm.corp)]/ > /dev/null 2>&1
+        # check if ab command was successful
+        if [ $? -ne 0 ]; then
+          echo "target: branch2vm.corp failed"
+          exit 1
+        else
+          echo "target: branch2vm.corp passed"
+        fi
+          ab -s 3 -n $1 -c $2 [$(get_ipv6 spoke1vm.eu.az.corp)]/ > /dev/null 2>&1
+        # check if ab command was successful
+        if [ $? -ne 0 ]; then
+          echo "target: spoke1vm.eu.az.corp failed"
+          exit 1
+        else
+          echo "target: spoke1vm.eu.az.corp passed"
+        fi
+          let i=i+1
+        sleep 5
+      done
+      EOF
+      chmod a+x /usr/local/bin/heavy-traffic-ipv6
+      
+      ########################################################
       # crontabs
       ########################################################
       
-      cat <<EOF > /etc/cron.d/traffic-gen
+      cat <<'EOF' > /etc/cron.d/traffic-gen
       */1 * * * * /usr/local/bin/light-traffic 2>&1 > /dev/null
-      */1 * * * * /usr/local/bin/heavy-traffic 50 1 2>&1 > /dev/null
-      */2 * * * * /usr/local/bin/heavy-traffic 8 2 2>&1 > /dev/null
-      */3 * * * * /usr/local/bin/heavy-traffic 20 4 2>&1 > /dev/null
-      */5 * * * * /usr/local/bin/heavy-traffic 15 2 2>&1 > /dev/null
+      */1 * * * * /usr/local/bin/heavy-traffic 15 1 2>&1 > /dev/null
+      */2 * * * * /usr/local/bin/heavy-traffic 3 1 2>&1 > /dev/null
+      */3 * * * * /usr/local/bin/heavy-traffic 8 2 2>&1 > /dev/null
+      */5 * * * * /usr/local/bin/heavy-traffic 5 1 2>&1 > /dev/null
       EOF
       
       crontab /etc/cron.d/traffic-gen
